api_endpoint: 127.0.0.1:5000
generation_settings:
  max_tokens: 256
  max_new_tokens: 128
  temperature: 0.6
  top_p: 0.85
  min_p: 0
  top_k: 40
  repetition_penalty: 1.2
  presence_penalty: 0.1
  frequency_penalty: 0.5
  typical_p: 1
  seed: -1 
